name: ansysToFoam
icon: view/config/content/1_Overview/images/ansysToFoam.svg

outputs:
  - foam_mesh

settings:
  "use_docker": true
  "docker_cmd": "docker run --name {docker_name} --rm -v {dice_workflow}:/usr/share/openfoam/data:Z dicehub/openfoam:4.1 \"{command}\""
  "foam_cmd": "/usr/bin/foamExec"
