en: >
  The snappyHexMesh utility generates 3-dimensional meshes containing
  hexahedra (hex) and split-hexahedra (split-hex) automatically from
  triangulated surface geometries in Stereolithography (STL) format. The mesh
  approximately conforms to the surface by iteratively refining a starting
  mesh and morphing the resulting split-hex mesh to the surface. An optional
  phase will shrink back the resulting mesh and insert cell layers.
  The specification of mesh refinement level is very flexible and the surface
  handling is robust with a pre-specified final mesh quality. It runs in
  parallel with a load balancing step every iteration.
  <br><br>(src: OpenFOAMWiki)
