before_script:
  - echo "Current DIR "$PWD

stages:
    - build_image
    - build_package
    
# Build image
# ===========
build docker image for dev:
    stage: build_image
    environment: development
    variables:
        CI_BUILD_TAG: "latest-dev"
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE:$CI_BUILD_TAG --build-arg VERSION="dev" .
        - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
    only:
        - dev
    tags:
        - image-builder

# Linux (latest-dev)
# ==================
x64_build:linux (dev):
    stage: build_package
    environment: development
    variables:
        VERSION: "latest-dev"
        CI_BUILD_TAG: "latest-dev"
    script:
        - docker run --rm -v $PWD:/home/dpm $CI_REGISTRY_IMAGE:$CI_BUILD_TAG python3 -m dpm build /home/dpm -o /home/dpm -v
        - rename 's/\.zip$/_dev.zip/' *zip
        - rsync -avR *.zip mcubcsro@backup1.foxcloud.net::mcubcsro/public/dice/apps/
        - rm -rf *.zip
    only:
        - dev
    tags:
        - dev-shell-executor-atlantic939
