version: '1'

name: 'OpenFOAM-4.1'
description: |
  'OpenFOAM package'
release: '18.01.1'

python: '{package_dir}/.venv'

linux:
  environ:
    LD_LIBRARY_PATH: '$LD_LIBRARY_PATH:{package_dir}/.venv/lib'
    PYTHONPATH: '$PYTHONPATH:{package_dir}/shared'
win:
  environ:
    PYTHONPATH: '$PYTHONPATH;{package_dir}\\shared'

apps:
  Solvers:
    Incompressible:
      - apps/simpleFoam
    #Multiphase:
      #- apps/interFoam
  Utilities:
    Mesh:
      #- apps/fluentMeshToFoam
      #- apps/ansysToFoam
      - apps/snappyHexMesh
    Python:
      - apps/Python Script
