name: snappyHexMesh
icon: view/config/content/1_Overview/images/ic_snappyHexMesh.svg

inputs:
  stl_files: 0
  parameters: 1
  
outputs:
  - foam_mesh

settings:
  "use_docker": true
  "docker_cmd": "docker run --name {docker_name} --rm -v {dice_workflow}:/usr/share/openfoam/data:Z dicehub/openfoam:4.1 \"{command}\""
  "foam_cmd": "/usr/bin/foamExec"
  "use_mpi": false
  "docker_cmd_mpi": "docker run --name {docker_name} --rm -v {dice_workflow}:/usr/share/openfoam/data:Z dicehub/openfoam:4.1 \"mpirun -np $NP {command} -parallel\""
  "foam_cmd_mpi": "/usr/bin/foamExec"
  "mpi_cpu_count": 1
